version: "3"
services:
  app:
    build: .
    ports:
     - 4200:4200
    networks:
      - default
    volumes:
      - .:/app/${APP_NAME}
      - node_modules/:/app/${APP_NAME}/node_modules
    command: ["bash"]
    tty: true
    stdin_open: true

volumes:
  node_modules:
    driver: local
