version: "3"
services:
  app:
    build: .
    ports:
     - 4200:4200
    networks:
      - default
    volumes:
      - .:/app/${APP_NAME}
      - node_modules/:/app/${APP_NAME}/node_modules
    working_dir: /app/${APP_NAME}
    command: ["ng", "serve", "--host", "0.0.0.0", "--poll", "1000"]
    tty: true
    stdin_open: true

volumes:
  node_modules:
    driver: local
